//! Acme UI is a compact, clean-room component starter library for GPUI.

mod primitives;
mod styled;
mod theme;

pub mod about_dialog;
pub mod accordion;
pub mod alert;
pub mod app_menu_bar;
pub mod autocomplete;
pub mod avatar;
pub mod badge;
pub mod breadcrumb;
pub mod button;
pub mod calendar;
pub mod card;
pub mod chart;
pub mod checkbox;
pub mod collapsible;
pub mod color_picker;
pub mod combobox;
pub mod command_palette;
pub mod context_toolbar;
pub mod date_picker;
pub mod date_range_picker;
pub mod dialog;
pub mod dock;
pub mod drag_region;
pub mod drawer;
pub mod drop_zone;
pub mod empty_state;
pub mod error_state;
pub mod field;
pub mod file_picker;
pub mod focus_ring;
pub mod focus_scope;
pub mod form;
pub mod form_message;
pub mod grid;
pub mod icon_button;
pub mod icons;
pub mod inspector_panel;
pub mod kbd;
pub mod label;
pub mod list;
pub mod loading_state;
pub mod markdown;
pub mod masked_input;
pub mod menu;
pub mod multi_select;
pub mod navigation_rail;
pub mod navigation_view;
pub mod notification;
pub mod number_input;
pub mod pagination;
pub mod password_input;
pub mod pin_input;
pub mod popover;
pub mod progress;
pub mod property_grid;
pub mod radio;
pub mod range_slider;
pub mod rating;
pub mod resizable;
pub mod resize_handle;
pub mod scroll_area;
pub mod search_input;
pub mod segmented_control;
pub mod select;
pub mod separator;
pub mod settings;
pub mod shortcut_manager;
pub mod sidebar;
pub mod skeleton;
pub mod slider;
pub mod spinner;
pub mod split_view;
pub mod stack;
pub mod status_bar;
pub mod stepper;
pub mod switch;
pub mod system_tray;
pub mod table;
pub mod tabs;
pub mod tag;
pub mod text_input;
pub mod textarea;
pub mod tiles;
pub mod time_picker;
pub mod title_bar;
pub mod toggle_button;
pub mod toolbar;
pub mod tooltip;
pub mod tree;
pub mod virtual_list;
pub mod window_controls;
pub mod window_overlay;

pub use primitives::{Size, Tone};
pub use styled::StyledExt;
pub use theme::{ActiveTheme, FontSizes, Spacing, Theme, ThemeColors, ThemeMode, hsl};

pub use about_dialog::AboutDialog;
pub use accordion::Accordion;
pub use alert::Alert;
pub use app_menu_bar::AppMenuBar;
pub use autocomplete::Autocomplete;
pub use avatar::Avatar;
pub use badge::Badge;
pub use breadcrumb::Breadcrumb;
pub use button::Button;
pub use calendar::Calendar;
pub use card::Card;
pub use chart::{BarChart, BarEntry};
pub use checkbox::Checkbox;
pub use collapsible::Collapsible;
pub use color_picker::ColorPicker;
pub use combobox::{Combobox, ComboboxOption};
pub use command_palette::CommandPalette;
pub use context_toolbar::ContextToolbar;
pub use date_picker::DatePicker;
pub use date_range_picker::DateRangePicker;
pub use dialog::Dialog;
pub use dock::{Dock, DockArea, DockPanel};
pub use drag_region::DragRegion;
pub use drawer::Drawer;
pub use drop_zone::DropZone;
pub use empty_state::EmptyState;
pub use error_state::ErrorState;
pub use field::FieldShell;
pub use file_picker::FilePicker;
pub use focus_ring::FocusRing;
pub use focus_scope::FocusScope;
pub use form::validators;
pub use form::{Field, Form};
pub use form_message::FormMessage;
pub use grid::Grid;
pub use icon_button::IconButton;
pub use icons::{Icon, IconName};
pub use inspector_panel::InspectorPanel;
pub use kbd::Kbd;
pub use label::Label;
pub use list::{List, ListItem};
pub use loading_state::LoadingState;
pub use loading_state::render_loading_state;
pub use markdown::Markdown;
pub use masked_input::MaskedInput;
pub use menu::{Menu, MenuItem};
pub use multi_select::MultiSelect;
pub use navigation_rail::NavigationRail;
pub use navigation_view::NavigationView;
pub use notification::{NotificationLevel, Notifications};
pub use number_input::NumberInput;
pub use pagination::Pagination;
pub use password_input::PasswordInput;
pub use pin_input::PinInput;
pub use popover::Popover;
pub use progress::Progress;
pub use property_grid::PropertyGrid;
pub use radio::{Radio, RadioGroup};
pub use range_slider::RangeSlider;
pub use rating::Rating;
pub use resizable::{Direction, Resizable};
pub use resize_handle::ResizeHandle;
pub use scroll_area::ScrollArea;
pub use search_input::SearchInput;
pub use segmented_control::SegmentedControl;
pub use select::{Select, SelectOption};
pub use separator::Separator;
pub use settings::{SettingsGroup, SettingsPage, SettingsRow};
pub use shortcut_manager::ShortcutManager;
pub use sidebar::Sidebar;
pub use skeleton::Skeleton;
pub use slider::Slider;
pub use spinner::Spinner;
pub use split_view::SplitView;
pub use stack::Stack;
pub use status_bar::StatusBar;
pub use stepper::Stepper;
pub use switch::Switch;
pub use system_tray::SystemTray;
pub use table::{SortDirection, Table, TableColumn};
pub use tabs::Tabs;
pub use tag::Tag;
pub use text_input::TextInput;
pub use textarea::Textarea;
pub use tiles::{Tile, TileDirection, Tiles};
pub use time_picker::TimePicker;
pub use title_bar::TitleBar;
pub use toggle_button::ToggleButton;
pub use toolbar::Toolbar;
pub use tooltip::Tooltip;
pub use tree::{Tree, TreeNode};
pub use virtual_list::VirtualList;
pub use window_controls::WindowControls;
pub use window_overlay::WindowOverlay;

use gpui::App;

/// Initializes Acme UI global state.
pub fn init(cx: &mut App) {
    theme::init(cx);
}
