//! inputs module.

pub mod autocomplete;
pub mod calendar;
pub mod checkbox;
pub mod color_picker;
pub mod combobox;
pub mod date_picker;
pub mod date_range_picker;
pub mod field;
pub mod file_picker;
pub mod form;
pub mod form_message;
pub mod masked_input;
pub mod multi_select;
pub mod number_input;
pub mod password_input;
pub mod pin_input;
pub mod radio;
pub mod range_slider;
pub mod rating;
pub mod search_input;
pub mod segmented_control;
pub mod select;
pub mod slider;
pub mod text_input;
pub mod textarea;
pub mod time_picker;
pub mod toggle_button;
